### PR TITLE
Add community sites ELB with ACM cert

### PR DESCRIPTION
**Pull request by flamingspaz**

### CODE REVIEW

**Comment by johngian** [comment]
Cert file got changed. Please use the new arn.

**Comment by johngian** [comment]
``terraform-plan`` shows

```
~ module.mesos-cluster-staging.aws_autoscaling_group.mesos-master-as
    load_balancers.#: "" => "<computed>"
~ module.mesos-cluster-production.aws_autoscaling_group.mesos-master-as
    load_balancers.#: "" => "<computed>"
```

Is that expected?

**Comment by johngian** [comment]
r+wc

**Comment by flamingspaz** [comment]
Yep, that var isn't set if there's only 1 elb.

**Pull request merged**
