### PR TITLE
add roadshow.rustbr.org distribution [bug 1419248]

### PR DESCRIPTION
**Pull request by TannerFilip**

### CODE REVIEW

**Comment by johngian** [comment]
@TannerFilip PR looks OK. But we also need the following:

* DNS entry pointing to the cloudfront distribution
* Update the certificate to also include the new certificate

@flamingspaz should we merge this and fix those afterwards?

**Comment by flamingspaz** [comment]
#174 will break this, lets hold off until friday.

**Comment by barrosgeraldo** [comment]
@TannerFilip there are anything from my side to move this forward? Can we ensure this done by end of year? If we can do it using this platform, there are any chance to manage this only under AWS DNS?

**Comment by flamingspaz** [comment]
This is unblocked again
@TannerFilip can you add the headers block like so https://github.com/mozilla/partinfra-terraform-cloudfrontssl/tree/secureheaders#examples
and change the source to `git://github.com/mozilla/partinfra-terraform-cloudfrontssl.git?ref=secureheaders`

**Comment by TannerFilip** [comment]
i've done that but also managed to massacre the git history.

**Pull request merged**
